### ISSUE TITLE
\input tdw

### ISSUE THREAD

**Issue by madneal** [DeathKing/LaTeX-Template-Cn#3]
不知道问这个问题好不好，从师兄那边传过来的一个论文模板，第二句话是这个，这个tex在windows系统可以正常编译，可是在mac下的texmaker却没有办法编译。我也不知道这个命令是什么意思，网上查也没有这样的东西，不知道您对这一块是否了解

**Comment by DeathKing** [comment]
Not good for disscus here. Closed.
