### ISSUE TITLE
中国人民大学论文模板

### ISSUE THREAD

**Issue by SLRXXX** [DeathKing/LaTeX-Template-Cn#4]
https://github.com/ZebinWang/ructhesis

**Comment by SLRXXX** [comment]
亲测好用，不过不知道该怎么加到当前repo里

**Comment by DeathKing** [comment]
@SLRXXX 推荐投稿到 http://www.latexstudio.net/ 。该网站比本仓库更专业、更齐全，而且维护团队更庞大。
