### ISSUE TITLE
用texstudio打开是论码

### ISSUE THREAD

**Issue by XULINGLI** [DeathKing/LaTeX-Template-Cn#5]
用texstudio打开是论码，求解决方案

**Comment by maxco2** [comment]
texlive可以正常编译

**Comment by EmingK** [comment]
目前模板文件使用 pdfLaTeX 编译，文档编码是 GBK。
你可以在 TeXstudio 的设置界面内调整默认的文档编码

**Comment by XULINGLI** [comment]
@EmingK 谢谢，已解决
